<div class="setting-option">	
	<h4 class="setting-title"><?php echo $title ?> :</h4>	
		
	<?php $checked = ( $value == 1 ) ? "checked='checked'" : '' ; ?> 
	<input type="checkbox" class="switchtoogle" value="1" name="<?php echo $id; ?>" id="<?php echo $id; ?>" <?php echo $checked; ?> />
	
	<span class="meta-description"><?php echo $description; ?></span>	
	<?php if(isset($help)) : ?>
	<div class="moreinfo" title="More Info">&nbsp;</div>
	<div class="help">
		<div class="help-wrapper">
			<?php echo $help; ?>
		</div>
	</div>
	<?php endif; ?>
</div>